name: navaja_suiza_sanitaria
description: La Navaja Suiza Sanitaria - Herramientas para profesionales de emergencias
publish_to: 'none'
version: 0.1.2+102

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1B3A5C"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#1B3A5C"
  image: "assets/icons/app_icon.png"
  android_12:
    color: "#1B3A5C"
    image: "assets/icons/app_icon.png"
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/
    - assets/version.json
